#!/usr/bin/env bash

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

detect_host_root() {
  local root

  # Prefer the host repo root when running inside a submodule.
  if root=$(git -C "$SCRIPT_DIR" rev-parse --show-superproject-working-tree 2>/dev/null) && [ -n "${root}" ]; then
    printf "%s" "$root"
    return 0
  fi

  # Fallback: normal git repo root.
  if root=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null) && [ -n "${root}" ]; then
    printf "%s" "$root"
    return 0
  fi

  # Non-git fallback.
  printf "%s" "$(pwd)"
}

HOST_ROOT="$(detect_host_root)"

RULES_FILE="$HOST_ROOT/.agency-rules.md"
GITIGNORE="$HOST_ROOT/.gitignore"

printf "%b\n" "${BLUE}=========================================${NC}"
printf "%b\n" "${BLUE}   AI Workforce: Initial Setup            ${NC}"
printf "%b\n" "${BLUE}=========================================${NC}"
printf "\n"
printf "This wizard configures the AI workforce for the host repository:\n"
printf "  %s\n\n" "$HOST_ROOT"

# 1. Check Dependencies
printf "%b\n" "${GREEN}[1/4] Checking Environment...${NC}"
if command -v opencode >/dev/null 2>&1; then
  printf "- opencode: found\n"
else
  printf "- opencode: NOT found (you can install later: npm install -g opencode)\n"
fi

if command -v node >/dev/null 2>&1; then
  printf "- node: found\n"
else
  printf "- node: NOT found (recommended for scripts/memory.js)\n"
fi

# 2. Configure Repo Rules (committed)
printf "\n"
printf "%b\n" "${GREEN}[2/4] Configuring Repository Rules...${NC}"

if [ -f "$RULES_FILE" ]; then
  printf "- Found existing %s\n" "$RULES_FILE"
  read -r -p "  Overwrite with a fresh template? (y/N) " overwrite
  if [ "${overwrite}" = "y" ]; then
    # Create a backup before overwriting.
    cp "$RULES_FILE" "$RULES_FILE.bak"
    : > "$RULES_FILE"
  fi
fi

if [ ! -f "$RULES_FILE" ] || [ ! -s "$RULES_FILE" ]; then
  {
    printf "# Agency Rules (Repository)\n"
    printf "\n"
    printf "This file is repository-level configuration for the AI workforce.\n"
    printf "It is intended to be committed to git.\n"
    printf "\n"
    printf "Generated by .agency/setup.sh on %s\n" "$(date)"
    printf "\n"
    printf "## Stack\n"
    printf "\n"
  } >> "$RULES_FILE"

  printf "Let's teach the AI about your stack.\n"

  read -r -p "  > Primary language (e.g. Python, TS, Go): " lang
  if [ -n "${lang}" ]; then
    printf "- Primary Language: %s\n" "$lang" >> "$RULES_FILE"
    printf "- Follow idiomatic coding standards for %s.\n" "$lang" >> "$RULES_FILE"
  fi

  read -r -p "  > Testing framework (e.g. Jest, Pytest): " test_fw
  if [ -n "${test_fw}" ]; then
    printf "- Testing Framework: %s\n" "$test_fw" >> "$RULES_FILE"
    printf "- All new features must include %s tests.\n" "$test_fw" >> "$RULES_FILE"
  fi

  read -r -p "  > Code style preference (e.g. Tabs, Semicolons): " style
  if [ -n "${style}" ]; then
    printf "- Code Style: %s\n" "$style" >> "$RULES_FILE"
  fi

  printf "- Wrote %s\n" "$RULES_FILE"
else
  printf "- Keeping existing %s\n" "$RULES_FILE"
fi

# 3. Gitignore (host repo)
printf "\n"
printf "%b\n" "${GREEN}[3/4] Configuring .gitignore (Host Repo)...${NC}"

if [ ! -f "$GITIGNORE" ]; then
  : > "$GITIGNORE"
fi

# Ensure local state stays untracked, but keep .agency-rules.md committed.
if grep -qE '^[[:space:]]*/?\.agency-rules\.md[[:space:]]*$' "$GITIGNORE"; then
  printf "- WARNING: %s currently ignores .agency-rules.md\n" "$GITIGNORE"
  read -r -p "  Remove that ignore entry so .agency-rules.md can be committed? (Y/n) " remove_ignore
  if [ "${remove_ignore}" != "n" ]; then
    tmp="$GITIGNORE.tmp.$$"
    grep -vE '^[[:space:]]*/?\.agency-rules\.md[[:space:]]*$' "$GITIGNORE" > "$tmp" || true
    mv "$tmp" "$GITIGNORE"
    printf "- Removed .agency-rules.md ignore entry\n"
  else
    printf "- Keeping ignore entry (you will NOT be able to commit .agency-rules.md)\n"
  fi
fi

AGENCY_BLOCK_START="# Agency Local State (ai-workforce)"
if ! grep -qF "$AGENCY_BLOCK_START" "$GITIGNORE"; then
  {
    printf "\n%s\n" "$AGENCY_BLOCK_START"
    printf "%s\n" ".agency-memory.json"
  } >> "$GITIGNORE"
fi

OPENCODE_BLOCK_START="# OpenCode Local State (ai-workforce)"
if ! grep -qF "$OPENCODE_BLOCK_START" "$GITIGNORE"; then
  {
    printf "\n%s\n" "$OPENCODE_BLOCK_START"
    printf "%s\n" ".opencode/"
  } >> "$GITIGNORE"
fi

printf "- Ensured local state is ignored in %s\n" "$GITIGNORE"

# 4. Finalize
printf "\n"
printf "%b\n" "${GREEN}[4/4] Setup Complete${NC}"
printf "-----------------------------------------\n"
printf "Next steps:\n"
printf "  1) Commit %s\n" "$RULES_FILE"
printf "  2) Run: opencode --config .agency/opencode.jsonc\n\n"

read -r -p "Start OpenCode now? (y/N) " start_now
if [ "${start_now}" = "y" ]; then
  opencode --config .agency/opencode.jsonc
fi
