#!/bin/bash

# .agency/setup.sh
# Interactive Setup Wizard for the AI Workforce

set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}   🤖 AI Workforce: Initial Setup        ${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""
echo "This wizard will configure the AI agents for this specific project."
echo ""

# 1. Check Dependencies
echo -e "${GREEN}[1/4] Checking Environment...${NC}"
if ! command -v opencode &> /dev/null; then
    echo "❌ 'opencode' is not installed or not in your PATH."
    echo "   Please install it first (e.g., npm install -g opencode)."
    exit 1
fi
echo "✅ 'opencode' found."

# 2. Configure Local Rules
echo ""
echo -e "${GREEN}[2/4] Configuring Project Rules...${NC}"
RULES_FILE=".agency-rules.md"

if [ -f "$RULES_FILE" ]; then
    read -p "   $RULES_FILE already exists. Overwrite? (y/N) " overwrite
    if [[ "$overwrite" != "y" ]]; then
        echo "   Skipping rules generation."
    else
        rm "$RULES_FILE"
    fi
fi

if [ ! -f "$RULES_FILE" ]; then
    echo "# Local Project Rules" > "$RULES_FILE"
    echo "These rules were generated by setup.sh on $(date)" >> "$RULES_FILE"
    echo "" >> "$RULES_FILE"

    echo "   Let's teach the AI about your stack."
    
    # Q: Language
    read -p "   > What is the primary programming language? (e.g. Python, TS, Go): " lang
    if [ ! -z "$lang" ]; then
        echo "- Primary Language: $lang" >> "$RULES_FILE"
        echo "- Follow idiomatic coding standards for $lang." >> "$RULES_FILE"
    fi

    # Q: Testing
    read -p "   > What testing framework do you use? (e.g. Jest, Pytest): " test_fw
    if [ ! -z "$test_fw" ]; then
        echo "- Testing Framework: $test_fw" >> "$RULES_FILE"
        echo "- All new features must include $test_fw tests." >> "$RULES_FILE"
    fi

    # Q: Style
    read -p "   > Any specific style preference? (e.g. Tabs, Semicolons): " style
    if [ ! -z "$style" ]; then
        echo "- Code Style: $style" >> "$RULES_FILE"
    fi

    echo "✅ Rules saved to $RULES_FILE"
fi

# 3. Git Configuration
echo ""
echo -e "${GREEN}[3/4] Securing Git...${NC}"
GITIGNORE=".gitignore"

if [ ! -f "$GITIGNORE" ]; then
    touch "$GITIGNORE"
fi

if ! grep -q ".agency-memory.json" "$GITIGNORE"; then
    echo "   Adding agency local state files to .gitignore..."
    echo "" >> "$GITIGNORE"
    echo "# Agency Local State" >> "$GITIGNORE"
    echo ".agency-memory.json" >> "$GITIGNORE"
    echo "✅ .gitignore updated."
else
    echo "✅ .gitignore already configured."
fi

# 4. Finalize
echo ""
echo -e "${GREEN}[4/4] Setup Complete!${NC}"
echo "-----------------------------------------"
echo "You are ready to go. To start the agents, run:"
echo ""
echo -e "   ${BLUE}opencode --config .agency/opencode.jsonc${NC}"
echo ""
read -p "Do you want to start the AI Workforce now? (y/N) " start_now
if [[ "$start_now" == "y" ]]; then
    opencode --config .agency/opencode.jsonc
fi
